#------------------------
#
# My first CI/CD pipeline
#
#------------------------

name: test-prep-actions
env:
  APPLICATION_NAME: "My repo deploy app"
  DEPLOY_PACKAGE_NAME    : "Repo package file = ${{github.sha}}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Pring Hello message
        run: echo "Hello world from testing job"
        
      - name: Execute few commands
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Hello message 3"
          echo "Application name is: ${{env.APPLICATION_NAME}}"
          
      - name: Pring current directory
        run: ls -la

      - name: Git clone my repo
        uses: actions/checkout@v1
      
      - name: Pring current directory
        run: ls -la
  
  my_deploy:
    runs-on: [ubuntu-latest]
    needs: [my_testing]
    
    env:
      VAR1: "My local variable VAR1 from my_deploy"
      VAR2: "My local variable VAR2 from my_deploy"
    
    steps:
      - name: Pring Hello message
        run: echo "Hello world from deploy job"
        
      - name: Pront local VARs
        run: |
          echo "VAR1 =  ${{env.VAR1}}"
          echo "VAR2 =  ${{env.VAR2}}"
          echo "VAR3 - super local one =  $env.LOCAL_VAR"
          
      env:
        LOCAL_VAR: "This is super local environment variable"
      
      - name: Printing deployment package
        run: echo "Deployment package is ${{env.DEPLOY_PACKAGE_NAME}}"
        
      - name: Let's test some packages if they are here 1
        run: aws --version

      - name: Let's test some packages if they are here 2
        run: zip

