name: test-prep-actions

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Pring Hello message
        run: echo "Hello world from testing job" >> file1.txt" 
      - name: Show file comtents
        run: cat file1.txt        
  
  my_deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Pring Hello message
        run: echo "Hello world from deploy job"
  
    
